name: toxic_bot_service
description: A server app for toxic bot functionality
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  shelf: 1.3.0
  shelf_router: 1.1.2
  json_annotation: 4.5.0
  injectable: 1.5.3
  get_it: 7.2.0
  recase: 4.0.0
  nyxx: 3.4.2
  dotenv: 4.0.1

dev_dependencies:
  http: 0.13.4
  lints: 2.0.0
  meta: 1.7.0
  json_serializable: 6.2.0
  build_runner: 2.1.10
  injectable_generator: 1.5.3
  dart_code_metrics: 4.15.1

assets:
  - .env
